Chapter-03/ActivityTracker/ActivityTracker/Models/ActivityModel.cs
using System.ComponentModel.DataAnnotations;

namespace ActivityTracker.Models
{
    public class ActivityModel
    {
        [Key]
        public int ActivityId { get; set; }
        [MaxLength(10)]
        public string Activity { get; set; }
        [MaxLength(25)]
        public string Action { get; set; }
        [MaxLength(65)]
        public string Description { get; set; }
        public string Data { get; set; }
    }
}

Chapter-03/ActivityTracker/ActivityTracker/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ActivityTracker.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }

        // GET: Dashboard/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Dashboard/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Dashboard/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dashboard/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Chapter-03/ActivityTracker/ActivityTracker/Controllers/TrackerController.cs
using System.Collections.Generic;
using System.Web.Http;
using ActivityTracker.Models;
using ActivityTracker.Persistance;

namespace ActivityTracker.Controllers
{
    public class TrackerController : ApiController
    {
        private readonly IActivityRepository _activityRepository;

        public TrackerController()
        {
            _activityRepository = new ActivityRepository();
        }

        public TrackerController(IActivityRepository activityRepository)
        {
            _activityRepository = activityRepository;
        }
        // GET api/<controller>
        public IEnumerable<ActivityModel> Get()
        {
            return _activityRepository.GetAll();
        }

        // GET api/<controller>/5
        public ActivityModel Get(int activityId)
        {
            return _activityRepository.GetBy(activityId);
        }

    }
}

Chapter-03/ActivityTracker/ActivityTracker/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Activity Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div ng-app="activityModule">
    <div class="container" ng-controller="activityController">
        <h2>Activity Dashboard</h2>
        <p>Glimpse of all activities of Bitbucket repository <c>repository name</c></p>
        <table class="table">
            <thead>
                <tr>
                    <th>Activity</th>
                    <th>Action</th>
                    <th>Description</th>
                    <th>Data</th>
                </tr>
            </thead>
            @{ int count = 0;}
            <tbody ng-repeat="activity in Activities">
                @{ count++;}
                <tr ng-class-odd="'warning'" ng-class-even="'success'">
                    <td>{{activity.Activity}}</td>
                    <td>{{activity.Action}}</td>
                    <td>{{activity.Description}}</td>
                    @*<td>{{activity.Data}}</td>*@
                    <td ng-click="getActivity({{activity.ActivityId}})">View Details</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@*@section scripts
{
    <script src="~/Scripts/app/app.js"></script>
    <script src="~/Scripts/app/controller.js"></script>
    <script src="~/Scripts/app/service.js"></script>
}*@

Chapter-03/ActivityTracker/ActivityTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    <script src="~/Scripts/app/app.js"></script>
    <script src="~/Scripts/app/controller.js"></script>
    <script src="~/Scripts/app/service.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Activity Dashboard", "Index", "Dashboard", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>